import type { Estimate, EstimateLineItem, EstimateWithLineItems } from "@/types";

// Mock estimates data
export const mockEstimates: Estimate[] = [
  {
    id: "est-001",
    projectId: "proj-001",
    name: "Shell Gas Station Demolition",
    description: "Complete interior demolition and hazmat removal",
    totalAmount: 45000,
    source: "manual",
    driveFileId: null,
    status: "approved",
    sentDate: new Date("2025-01-05"),
    approvedDate: new Date("2025-01-08"),
    notes: null,
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-08"),
  },
  {
    id: "est-002",
    projectId: "proj-002",
    name: "TD Bank Demolition & Restoration",
    description: "Interior demolition with asbestos abatement",
    totalAmount: 72500,
    source: "manual",
    driveFileId: null,
    status: "sent",
    sentDate: new Date("2025-01-10"),
    approvedDate: null,
    notes: "Awaiting client response",
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    id: "est-003",
    projectId: "proj-003",
    name: "Petro-Can Kamloops",
    description: "Full site demolition including underground tanks",
    totalAmount: 125000,
    source: "imported",
    driveFileId: "drive-file-123",
    status: "approved",
    sentDate: new Date("2024-12-15"),
    approvedDate: new Date("2024-12-20"),
    notes: null,
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-20"),
  },
];

// Mock line items
export const mockLineItems: Record<string, EstimateLineItem[]> = {
  "est-001": [
    {
      id: "li-001",
      estimateId: "est-001",
      category: "labor",
      description: "Demolition crew (4 workers x 5 days)",
      quantity: 20,
      unit: "day",
      unitPrice: 600,
      totalPrice: 12000,
      sortOrder: 0,
      notes: null,
      createdAt: new Date("2025-01-03"),
      updatedAt: new Date("2025-01-03"),
    },
    {
      id: "li-002",
      estimateId: "est-001",
      category: "equipment",
      description: "Excavator rental",
      quantity: 5,
      unit: "day",
      unitPrice: 1200,
      totalPrice: 6000,
      sortOrder: 1,
      notes: null,
      createdAt: new Date("2025-01-03"),
      updatedAt: new Date("2025-01-03"),
    },
    {
      id: "li-003",
      estimateId: "est-001",
      category: "materials",
      description: "Disposal bins (30 yard)",
      quantity: 4,
      unit: "each",
      unitPrice: 850,
      totalPrice: 3400,
      sortOrder: 2,
      notes: null,
      createdAt: new Date("2025-01-03"),
      updatedAt: new Date("2025-01-03"),
    },
    {
      id: "li-004",
      estimateId: "est-001",
      category: "subcontractors",
      description: "Hazmat removal specialist",
      quantity: 1,
      unit: "lump sum",
      unitPrice: 18000,
      totalPrice: 18000,
      sortOrder: 3,
      notes: "Includes asbestos testing and removal",
      createdAt: new Date("2025-01-03"),
      updatedAt: new Date("2025-01-03"),
    },
    {
      id: "li-005",
      estimateId: "est-001",
      category: "permits",
      description: "Demolition permit",
      quantity: 1,
      unit: "each",
      unitPrice: 2500,
      totalPrice: 2500,
      sortOrder: 4,
      notes: null,
      createdAt: new Date("2025-01-03"),
      updatedAt: new Date("2025-01-03"),
    },
    {
      id: "li-006",
      estimateId: "est-001",
      category: "other",
      description: "Site cleanup and restoration",
      quantity: 1,
      unit: "lump sum",
      unitPrice: 3100,
      totalPrice: 3100,
      sortOrder: 5,
      notes: null,
      createdAt: new Date("2025-01-03"),
      updatedAt: new Date("2025-01-03"),
    },
  ],
  "est-002": [
    {
      id: "li-007",
      estimateId: "est-002",
      category: "labor",
      description: "Demolition team (6 workers x 8 days)",
      quantity: 48,
      unit: "day",
      unitPrice: 550,
      totalPrice: 26400,
      sortOrder: 0,
      notes: null,
      createdAt: new Date("2025-01-08"),
      updatedAt: new Date("2025-01-08"),
    },
    {
      id: "li-008",
      estimateId: "est-002",
      category: "subcontractors",
      description: "Asbestos abatement contractor",
      quantity: 1,
      unit: "lump sum",
      unitPrice: 28000,
      totalPrice: 28000,
      sortOrder: 1,
      notes: "Certified AHERA contractor",
      createdAt: new Date("2025-01-08"),
      updatedAt: new Date("2025-01-08"),
    },
    {
      id: "li-009",
      estimateId: "est-002",
      category: "equipment",
      description: "Heavy equipment rental",
      quantity: 8,
      unit: "day",
      unitPrice: 1500,
      totalPrice: 12000,
      sortOrder: 2,
      notes: null,
      createdAt: new Date("2025-01-08"),
      updatedAt: new Date("2025-01-08"),
    },
    {
      id: "li-010",
      estimateId: "est-002",
      category: "materials",
      description: "Debris disposal",
      quantity: 1,
      unit: "lump sum",
      unitPrice: 4500,
      totalPrice: 4500,
      sortOrder: 3,
      notes: null,
      createdAt: new Date("2025-01-08"),
      updatedAt: new Date("2025-01-08"),
    },
    {
      id: "li-011",
      estimateId: "est-002",
      category: "permits",
      description: "Work permits",
      quantity: 1,
      unit: "each",
      unitPrice: 1600,
      totalPrice: 1600,
      sortOrder: 4,
      notes: null,
      createdAt: new Date("2025-01-08"),
      updatedAt: new Date("2025-01-08"),
    },
  ],
  "est-003": [
    {
      id: "li-012",
      estimateId: "est-003",
      category: "labor",
      description: "Site demolition crew",
      quantity: 30,
      unit: "day",
      unitPrice: 1200,
      totalPrice: 36000,
      sortOrder: 0,
      notes: null,
      createdAt: new Date("2024-12-10"),
      updatedAt: new Date("2024-12-10"),
    },
    {
      id: "li-013",
      estimateId: "est-003",
      category: "subcontractors",
      description: "Underground tank removal specialist",
      quantity: 1,
      unit: "lump sum",
      unitPrice: 45000,
      totalPrice: 45000,
      sortOrder: 1,
      notes: "Includes soil testing",
      createdAt: new Date("2024-12-10"),
      updatedAt: new Date("2024-12-10"),
    },
    {
      id: "li-014",
      estimateId: "est-003",
      category: "equipment",
      description: "Heavy machinery",
      quantity: 15,
      unit: "day",
      unitPrice: 2000,
      totalPrice: 30000,
      sortOrder: 2,
      notes: null,
      createdAt: new Date("2024-12-10"),
      updatedAt: new Date("2024-12-10"),
    },
    {
      id: "li-015",
      estimateId: "est-003",
      category: "permits",
      description: "Environmental permits",
      quantity: 1,
      unit: "each",
      unitPrice: 8000,
      totalPrice: 8000,
      sortOrder: 3,
      notes: null,
      createdAt: new Date("2024-12-10"),
      updatedAt: new Date("2024-12-10"),
    },
    {
      id: "li-016",
      estimateId: "est-003",
      category: "other",
      description: "Contingency",
      quantity: 1,
      unit: "lump sum",
      unitPrice: 6000,
      totalPrice: 6000,
      sortOrder: 4,
      notes: null,
      createdAt: new Date("2024-12-10"),
      updatedAt: new Date("2024-12-10"),
    },
  ],
};

// Helper functions
export function getEstimateById(id: string): Estimate | null {
  return mockEstimates.find((e) => e.id === id) || null;
}

export function getEstimateByProjectId(projectId: string): Estimate | null {
  return mockEstimates.find((e) => e.projectId === projectId) || null;
}

export function getEstimateWithLineItems(estimateId: string): EstimateWithLineItems | null {
  const estimate = getEstimateById(estimateId);
  if (!estimate) return null;
  return {
    ...estimate,
    lineItems: mockLineItems[estimateId] || [],
  };
}

export function getEstimateWithLineItemsByProjectId(projectId: string): EstimateWithLineItems | null {
  const estimate = getEstimateByProjectId(projectId);
  if (!estimate) return null;
  return {
    ...estimate,
    lineItems: mockLineItems[estimate.id] || [],
  };
}

// Create empty estimate for new projects
export function createEmptyEstimate(projectId: string, projectName: string): EstimateWithLineItems {
  return {
    id: `temp-${Date.now()}`,
    projectId,
    name: projectName,
    description: null,
    totalAmount: 0,
    source: "manual",
    driveFileId: null,
    status: "draft",
    sentDate: null,
    approvedDate: null,
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    lineItems: [],
  };
}
